name: notify-owners
description: Notify code owners of changes
inputs:
  owners_file_name:
    description: Name of owners files
    required: false
    default: OWNERS
  max_num_owners:
    description: Maximum number of owners to notify, 0 to disable
    required: false
    default: "100"
  max_num_files:
    description: Maximum number of files to display, 0 to disable
    required: false
    default: "100"
runs:
  using: docker
  image: Dockerfile
  args:
    - github
branding:
  icon: bell
  color: yellow
