name: pr-build
on:
  - pull_request
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.2'
      - run: make build
      - run: make test
      - run: make lint
