name: pr-notify
on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
jobs:
  owners-notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./ # If you were using this in your project, this would be sourcegraph/codenotify@vX.Y.Z (check releases on GitHub for latest version number)
        env:
          # This token needs to have repo scope and read:org scope (to be able to mention teams).
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
